### PR TITLE
elliptic envelope

### PR DESCRIPTION
**Pull request by igorisolomon**

### CODE REVIEW

**Comment by Jolomi-Tosanwumi** [comment]
Hi @igorisolomon ...nice work from you. Here are my observations and recommendations:

1. Please use random state of 1, and test_size of 0.25 so we can have a common ground for comparing our model.
2. For your stratified K fold object, kindly set shuffle to True, nsplit to 4 and random state to 1.
3. It seems you didn't scale the data, please do and be sure to avoid data leakage when scaling.
4. The f1score you have is actually for not fraud class because you reset fraud to -1 and not fraud class to 1. You know the default pos_label for f1score is 1. To get around this, you may want to set pos_label to -1 in the make_scorer function.

Overall, a good job. Please kindly effect these corrections.
Thank you.

**Comment by Bennykillua** [comment]
just make the necessary correction.

@Jolomi-Tosanwumi "Hi @igorisolomon ...nice work from you. Here are my observations and recommendations:

Please use random state of 1, and test_size of 0.25 so we can have a common ground for comparing our model.
For your stratified K fold object, kindly set shuffle to True, nsplit to 4 and random state to 1.
It seems you didn't scale the data, please do and be sure to avoid data leakage when scaling.
The f1score you have is actually for not fraud class because you reset fraud to -1 and not fraud class to 1. You know the default pos_label for f1score is 1. To get around this, you may want to set pos_label to -1 in the make_scorer function.
Overall, a good job. Please kindly effect these corrections.
Thank you."

**Comment by igorisolomon** [comment]
@Jolomi-Tosanwumi @Bennykillua @Uthmanic
The recommendations have been effected

**Comment by Bennykillua** [comment]
this right https://github.com/igorisolomon/g01-fraud-detection/blob/master/model/Anomaly%20Detection%20models/elliptic_envelope.ipynb 

thought we were to use stander scaler?

**Comment by igorisolomon** [comment]
I used minmax scaler

**Comment by Jolomi-Tosanwumi** [comment]
Well done @igorisolomon ...although, there seems to be data leakage; it seems elliptic envelope is not the best model for our dataset since it only does outlier detection and not novelty detection. Overall nice job from you.

**Comment by Jolomi-Tosanwumi** [comment]
Hi @igorisolomon ...there seem to be conflict between your forked repo and the base branch. To resolve it, kindly delete your forked repo and refork the base repo. Be sure to have your notebook (elliptic envelope) saved somewhere else so you can commit it to your reforked repo and then make a new pull request.

I am closing this pull request now. Please resolve the conflict and make a pull request.

Thank you.

**Pull request closed without merging**
