### PR TITLE
Used cost sensitive XGBoost as the final model

### PR DESCRIPTION
**Pull request by Jolomi-Tosanwumi**
Used calibrated cost sensitive XGBoost as the final model

Find the notebook for kubeflow and deployment [here](https://github.com/Jolomi-Tosanwumi/g01-fraud-detection/blob/master/model/final-model-v2.ipynb)

### CODE REVIEW

**Comment by kene111** [comment]
Looks good, would work on it tonight.

**Comment by moreira-presh** [comment]
Good to go

**Comment by Jolomi-Tosanwumi** [comment]
Hi @Bennykillua  @Triomphi  @phil-blu , find our workflow image [here](https://github.com/Jolomi-Tosanwumi/g01-fraud-detection/blob/master/images/fraud_detection_workflow.png)

**Comment by Jolomi-Tosanwumi** [comment]
Hi @Bennykillua  @phil-blu  @Triomphi  @Uthmanic, find useful analysis and results of our model for presentation slide and article  [here](https://github.com/Jolomi-Tosanwumi/g01-fraud-detection/blob/master/model/final-model-analysis.ipynb)

**Comment by Bennykillua** [comment]
Thanks @Jolomi-Tosanwumi  we are good to go

**Pull request merged**
