### PR TITLE
XGBoost

### PR DESCRIPTION
**Pull request by moreira-presh**
Check the link [here](https://github.com/moreira-presh/g01-fraud-detection/blob/master/model/XGBOOST.ipynb)

### CODE REVIEW

**Comment by Jolomi-Tosanwumi** [comment]
Hi @moreira-presh ....this is great. Well done. It seems the cost sensitive model is the best with XGBoost. Will incorporate it to our final model.

Nice job.

**Comment by moreira-presh** [comment]
Thanks...
I'll start working on the other regarding amount and time on fraud detection

**Comment by Jolomi-Tosanwumi** [comment]
Hi @moreira-presh, please use the 27 selected features in the updated version of our baseline model. They will give a better f1score. Find the updated baseline model in the HamoyeHQ repo.

Thanks.

**Comment by moreira-presh** [comment]
@Jolomi-Tosanwumi  the f1 score improved by 0.001 which is quite good.
I will add it up now to the model

Here is the [link](https://github.com/moreira-presh/g01-fraud-detection/blob/1021a5b9e85cb914fdb86bb5766d0621d8a9ee29/model/XGBOOST(1).ipynb)

**Pull request merged**
