### PR TITLE
Gradient Boosting Classifier

### LINKED ISSUE #5: Gradient Boosting Trees
Your task is to model with gradient boosting trees.

### PR DESCRIPTION
**Pull request by Uthmanic**
I got negative cost savings figures after downsampling and upsampling, but the f1_score and precision_recall are both good. What does this means? [here's the notebook](https://github.com/Uthmanic/g01-fraud-detection/blob/master/model/ML%20models/Gradient%20Boosting.ipynb)

### CODE REVIEW

**Comment by Jolomi-Tosanwumi** [comment]
Hi @Uthmanic ...it is due to data leakage because you applied SMOTE and undersampled before splitting your data. Preprocessing like resampling should be done to the training set only so your model doesn't see copies of the training set in the testing set which will give false evaluation results. Using imblearn's pipeline will handle this for you. You may also want to include the scaler to the pipeline too to further prevent data leakages.

Thank you.

**Comment by Uthmanic** [comment]
gradie

why am i getting this error? help me look into it

**Comment by moreira-presh** [comment]
Ljke @Jolomi-Tosanwumi  said...
Applying smote and resampling is preferable after splitting

**Comment by Uthmanic** [comment]
Yeah, but I'm not doing any of that in this case. I followed the baseline notebook

**Comment by Jolomi-Tosanwumi** [comment]
Hi @Uthmanic kindly refer to the updated baseline model for the updated features to use.

For the error message, it seems cross validate function encountered an internal error but the error was passed silently. Set error_score='raise' in the cross validate function so we see the actual error that is been raised.

**Comment by Uthmanic** [comment]
Hi @Jolomi-Tosanwumi, i have updated my model. I had to remove the sample weights when training both SMOTE & Undesampling models, because i keep getting an error _"ValueError: not enough values to unpack (expected 2, got 1)"_
and the F1-score is really poor.

**Comment by Jolomi-Tosanwumi** [comment]
Hi @Uthmanic ...job well done. The model is looking great. SMOTE and Undersampling are giving poor results probably because they may not be the best preprocessing for our dataset. The cost sensitive model looks promising. You may want to improve your model's performance if you wish by tuning some useful hyper parameters.

Overall nice job and it got my approval to be merged.

Thank you.

**Review by Jolomi-Tosanwumi — APPROVED** [review]

**Comment by Jolomi-Tosanwumi** [comment]
Others can be please help review and comment to be sure we aren't missing anything. 

Thank you.

**Comment by Bennykillua** [comment]
The cost sensitive model  looks good

**Comment by moreira-presh** [comment]
Lemme go through it now...

**Pull request merged**
