### PR TITLE
Adding MLP model notebook.

### LINKED ISSUE #1: MLP
Your task is to model using MLP

### PR DESCRIPTION
**Pull request by Jolomi-Tosanwumi**
Modeled with Multi-Layer Perceptron (MLP) which is a deep learning model.

Kindly find the MLP notebook [here](https://github.com/Jolomi-Tosanwumi/g01-fraud-detection/blob/master/model/DL%20models/mlp.ipynb)

### CODE REVIEW

**Comment by Jolomi-Tosanwumi** [comment]
I am closing this pull request now...want to correct some typos in some markdown cell. Will re-open it when I am done.

**Comment by Jolomi-Tosanwumi** [comment]
Done correcting the typos.

**Comment by Jolomi-Tosanwumi** [comment]
In addition to my MLP pull request, kindly review my changes to the baseline model where I fitted scaler on only the training set and used it to transform both training and testing set using a data pipeline to avoid data leakage.

Kindly find the notebook [here](https://github.com/Jolomi-Tosanwumi/g01-fraud-detection/blob/master/model/baseline-model.ipynb)

**Comment by moreira-presh** [comment]
This looks good.. 
Other than a not so high f1score and cost saving, it's okay

**Comment by Bennykillua** [comment]
looks okay. you mentiioned a change to the baseline.

**Pull request merged**
