### PR TITLE
Adding the ensemble model and the first version of our final model

### PR DESCRIPTION
**Pull request by Jolomi-Tosanwumi**
Find the mlp and knn ensemble notebook [here](https://github.com/Jolomi-Tosanwumi/g01-fraud-detection/blob/master/model/mlp_knn_ensemble.ipynb) NOTE: This notebook runs for 7hrs+. Be sure that you really wan to run it before running it.

Kindly find the first version of our final model [here](https://github.com/Jolomi-Tosanwumi/g01-fraud-detection/blob/master/model/Final_model_v1.ipynb). The notebook is useful for deployment @kene111 @Johnnols. Voting ensemble was used for this notebook because it seems to be the best ensemble strategy from the mlp_knn_ensemble notebook.

### CODE REVIEW

**Comment by Jolomi-Tosanwumi** [comment]
Please review and comment. Thank you.

**Comment by Justus-coded** [comment]
The notebooks look great. Well done @Jolomi-Tosanwumi .

**Comment by Jolomi-Tosanwumi** [comment]
Hi guys, new update in version 1 of our final model.

I calculated the cost saving for prediction. As a result, the following changes were made:

1. defined a new function prediction_summary that nicely print and return predictions after calling get_predictions function.
2. get_predictions function was modified to allow return of probability scores.
3. ColumnSelector transfomer was modified to allow 1-dimensional numpy array as input.

Please take note of these updates @kene111 @Johnnols and Opeyemi 

Find the notebook with same link above in the first comment.

Thank you.

**Comment by Bennykillua** [comment]
noteboook looks good. we wouldnt be testing out the other models?

**Comment by moreira-presh** [comment]
Very good...
How many models are you looking to ensemble @Jolomi-Tosanwumi

**Comment by moreira-presh** [comment]
I'm not so sure, maybe because of time @Bennykillua..
Or the ones with good metrics could be incorporated

**Comment by Jolomi-Tosanwumi** [comment]
> Very good...
> How many models are you looking to ensemble @Jolomi-Tosanwumi

As much good models that beat our 0.8 f1_score threshold as we can @moreira-presh

**Comment by Jolomi-Tosanwumi** [comment]
@kene111 has told me that the serialized knn model is larger than 100MB and can't be uploaded to github because of the size. The size may also increase slug size in heroku as a result, I updated the final model v1 notebook to serialize the preprocessed data instead. KNN uses lazy machine learning by doing nothing but simply storing the training set during fitting. It only look for nearest neighbor during predict method. So, serializing the preprocessed data saved us some memory (more than 50%) compared to serializing the fitted knn object. 

Updates were made to the session of serializing knn model using dill. I serialized the preprocessed training set and the y labels instead. Changes were also made to the get_predictions function. To avoid name conflicting, Xt was used as the variable name for the transformed user's input in the get_predictions function. Find the updated notebook using the same link in my first comment in this thread.

@kene111  @Johnnols , please take note.

Thank you.

**Comment by kene111** [comment]
@Jolomi-Tosanwumi Noted the changes. I would make corrections this night.

**Comment by Johnnols** [comment]
Noted @Jolomi-Tosanwumi

**Comment by moreira-presh** [comment]
great work guys

**Pull request merged**
