### PR TITLE
Eda on time and amount

### PR DESCRIPTION
**Pull request by DevAdeola**
#### Find the notebook [here](https://github.com/DevAdeola/g01-fraud-detection/blob/master/EDA_and_preprocessing/eda_on_time_and_amount.ipynb) and images folder [here](https://github.com/DevAdeola/g01-fraud-detection/tree/master/images)

### CODE REVIEW

**Comment by Bennykillua** [comment]
hanks for this @DevAdeola this will be useful in the presentation @Triomphi

**Comment by Triomphi** [comment]
Yeah this will make sense, as visualizations will be faster to understand than words

**Comment by AlxeverCodeX** [comment]
This visualization is really good

**Comment by Bennykillua** [comment]
should take off the last line of code. it conflit with our current number of features

**Comment by moreira-presh** [comment]
good one bro

**Comment by Bennykillua** [comment]
@Jolomi-Tosanwumi  https://github.com/HamoyeHQ/g01-fraud-detection/pull/53#issuecomment-744332412

**Comment by moreira-presh** [comment]
I did something [HERE](https://github.com/moreira-presh/g01-fraud-detection/blob/04c9752af666ddbe7d3183409f8705ab200090bb/EDA_and_preprocessing/Untitled10.ipynb) which is similar to what @DevAdeola did, just a little addition.

**Comment by DevAdeola** [comment]
> should take off the last line of code. it conflit with our current number of features

Will do that now

**Comment by moreira-presh** [comment]
I wasn't able to really do much with the Time feature because it wasn't fully represented, using it as Date-time wont work because we will have to make do with the default "00-01-1960"  value, and the conversion too

**Pull request merged**
