### PR TITLE
Added notebook for SGDClassifier

### LINKED ISSUE #15: SGD
Your task is to model with Stochastic Gradient Descent.

### PR DESCRIPTION
**Pull request by Justus-coded**
Here i built a model using SDGClassifier. The notebook can be found [here](https://github.com/Justus-coded/g01-fraud-detection/blob/master/model/ML%20models/SGDClassifier.ipynb). Kindly review.

### CODE REVIEW

**Comment by Jolomi-Tosanwumi** [comment]
Well done @Justus-coded , great job. Just to add, from your work, I perceive not setting class_weight for the fraud sensitive model should give a higher f1_score. You may want to try that and include it in your notebook.

Thank you.

**Comment by Bennykillua** [comment]
seem he has added the weight class

**Comment by Justus-coded** [comment]
I have reviewed the code, it turns out that not setting class weights for the fraud sensitive model improves the f1 score. Find attached the code [here](https://github.com/Justus-coded/g01-fraud-detection/blob/master/model/ML%20models/SGDClassifier.ipynb)

**Comment by moreira-presh** [comment]
Yea it improved your model, it could mean its not a good one for fraud detection as can be seen with the f1 score without  adding class_weights

**Comment by Bennykillua** [comment]
uhmmm i don't think that is a good thing. that means it isn't great for this particular problem

**Comment by Justus-coded** [comment]
I agree @moreira-presh @Bennykillua

**Pull request merged**
