### PR TITLE
Created Pipeline 

### PR DESCRIPTION
**Pull request by kene111**
Link to the note book can be found [here](https://github.com/kene111/g01-fraud-detection/blob/master/pipeline/Fraud%20Detection%20Pipeline.ipynb), If any mistakes are found, please do let me know.

### CODE REVIEW

**Comment by Jolomi-Tosanwumi** [comment]
This looks great and is excellently done. Like you told me, I forgot to return the cost saving metric in the final model. Since it is such an important metric, I will update the final model to implement that. This may require you to re-update the pipeline. Sorry for the inconveniency .

**Comment by kene111** [comment]
@Jolomi-Tosanwumi Alright, no problem at all.

**Comment by moreira-presh** [comment]
This looks great @kene111

**Comment by kene111** [comment]
@moreira-presh Thank you.

**Comment by Bennykillua** [comment]
Looks great

**Comment by kene111** [comment]
Made changes to the pipeline, the notebook can be found [here](https://github.com/kene111/g01-fraud-detection/blob/master/pipeline/Fraud%20Detection%20Pipeline.ipynb). Serialized objects can be found [here](https://github.com/kene111/g01-fraud-detection/tree/master/pipeline/serialized%20objects).

**Comment by Jolomi-Tosanwumi** [comment]
Nice one @kene111

**Comment by Johnnols** [comment]
Great job @kene111

**Comment by kene111** [comment]
Thanks @Johnnols

**Comment by kene111** [comment]
Created the pipeline for the finalized model. Notebook can be found [here](https://github.com/kene111/g01-fraud-detection/blob/master/pipeline/Fraud%20Detection%20Pipeline%20Final%20Model.ipynb). Serialized objects can be found [here](https://github.com/kene111/g01-fraud-detection/tree/master/pipeline/serialized%20objects).

**Comment by Johnnols** [comment]
You've updated the pipeline right @kene111
I'd use that in building the flask app I'm working on

**Comment by Jolomi-Tosanwumi** [comment]
> You've updated the pipeline right @kene111
> I'd use that in building the flask app I'm working on

Hi @Johnnols , The pipeline wasn't actually meant for deployment but for experimentation and evaluation. If you noticed, in the pipeline; we split the data into train and test set. We trained on train and tested on test for model evaluation. But for deployment; we need to train on our whole dataset to maximize learning for any user's input and that is exactly what I did in the final_model_v2 notebook. I created it for deployment and you may want to refer to it. You may also refer to the pipeline but just be aware that we are to train on the whole dataset for deployment.

Thank you.

**Comment by kene111** [comment]
@Jolomi-Tosanwumi  If that is the case, I would create another pipeline for deployment. Basically just train the model on the whole dataset so @Johnnols can use the serialized model.

**Comment by Jolomi-Tosanwumi** [comment]
Alright @kene111

**Comment by Johnnols** [comment]
So, if we do it this way, there's no way to test our deployed model tho.
Or aren't we supposed to test the deployed model by passing in some parameters we know the outcome of?

**Comment by Johnnols** [comment]
Good Job @kene111 and @Jolomi-Tosanwumi

**Comment by kene111** [comment]
Alright, so you can find the serialized objects for deployment [here](https://github.com/kene111/g01-fraud-detection/tree/master/pipeline/serialized%20objects). The notebook is found [here](https://github.com/kene111/g01-fraud-detection/blob/master/pipeline/Fraud%20Detection%20Deployment%20Model%20Pipeline.ipynb).

**Comment by Jolomi-Tosanwumi** [comment]
> So, if we do it this way, there's no way to test our deployed model tho.
> Or aren't we supposed to test the deployed model by passing in some parameters we know the outcome of?

@Johnnols , we can use any of the trained observation (which is from our whole dataset) to test our deployed model. For model evaluation, we have done that in our modeling and choice of model where we trained on train and tested on test.

**Comment by Bennykillua** [comment]
is this for the webapp?

**Comment by Jolomi-Tosanwumi** [comment]
> is this for the webapp?

It can be used for the app but it is mainly a pipeline for our work.

**Comment by Jolomi-Tosanwumi** [comment]
Nice one @kene111

**Review by Jolomi-Tosanwumi — APPROVED** [review]

**Pull request merged**
