### PR TITLE
KNN model

### PR DESCRIPTION
**Pull request by Bennykillua**
Modeled with k-nearest neighbors algorithm.

Kindly find the MLP notebook [here] (https://github.com/Bennykillua/g01-fraud-detection/blob/master/model/ML%20models/baseline-model-KNN.ipynb)

will add a second model later. it is still running

### CODE REVIEW

**Comment by Bennykillua** [comment]
@oladapo-joseph @Uthmanic @Jolomi-Tosanwumi @moreira-presh

**Comment by Jolomi-Tosanwumi** [comment]
Hi @Bennykillua ...good job. Only that you used a random state of 0 instead of 1, but it shouldn't change much. Good model, and it got my approval. Let's others review and comment, but from my end, it is OK to be merged once you correct the random state to 1.

Thank you.

**Review by Jolomi-Tosanwumi — APPROVED** [review]

**Comment by Bennykillua** [comment]
will update the random_state. currently re-running my notebook

**Comment by Bennykillua** [comment]
done

**Pull request merged**
