### PR TITLE
added EDA notebook

### LINKED ISSUE #4: EDA

### PR DESCRIPTION
**Pull request by Jolomi-Tosanwumi**
Find the EDA notebook [here](https://github.com/Jolomi-Tosanwumi/g01-fraud-detection/blob/master/EDA_and_preprocessing/eda_and_data_cleaning.ipynb)

Find the baseline model notebook [here](https://github.com/Jolomi-Tosanwumi/g01-fraud-detection/blob/master/baseline-model.ipynb)

### CODE REVIEW

**Comment by Uthmanic** [comment]
thank you for the guide. I'm finding it difficult using class weight with GradientBoosting Classifier.

**Comment by Uthmanic** [comment]
here is the [notebook](https://github.com/Uthmanic/g01-fraud-detection/blob/master/GradientBoosting.ipynb)

**Comment by Jolomi-Tosanwumi** [comment]
OK @Uthmanic...it seems class weight hyper-parameter is not available in gradient boosting tree probably because it is robust to class imbalance. We can model without setting the class weight hyper-parameter for gradient boosting tree.

**Comment by oladapo-joseph** [comment]
The eda looks good

**Comment by oladapo-joseph** [comment]
I think we can merge the baseline model and the eda file too

**Review by oladapo-joseph — APPROVED** [review]

**Review by Uthmanic — APPROVED** [review]

**Comment by Uthmanic** [comment]
@Jolomi-Tosanwumi i did that, the result is not really good
i also applied smote and i got auc score of around 0.91, but i don't know how to implement cost savings, the whole thing is a little confusing-- [notebook](https://github.com/HamoyeHQ/g01-fraud-detection/blob/master/GradientBoosting.ipynb)

**Comment by Jolomi-Tosanwumi** [comment]
> I think we can merge the baseline model and the eda file too

Alright @oladapo-joseph thank you for approval. Will merge it right away.

**Comment by Jolomi-Tosanwumi** [comment]
> @Jolomi-Tosanwumi i did that, the result is not really good
> i also applied smote and i got auc score of around 0.91, but i don't know how to implement cost savings, the whole thing is a little confusing-- [notebook](https://github.com/HamoyeHQ/g01-fraud-detection/blob/master/GradientBoosting.ipynb)

Hi @Uthmanic...gone through the notebook and it looks great. Nice job done but, the AUC you calculated is ROC AUC which may be misleading for imbalanced dataset like ours. ROC AUC is a balanced measurement  of True positive rate and True negative rate. The high score is due to the high True negative rate which we would normally expect because the negative class is the majority class.

We may want to use average precision metric which is same as Precision-Recall AUC. This is more suitable for imbalanced dataset. For the low performance of your model, you may want to tune some hyper-parameters.
For the cost savings; check the baseline model to see how I implemented it. I will also give brief explanation on the cost sensitive and saving strategy in our tomorrow. Meanwhile, [this article](https://towardsdatascience.com/fraud-detection-with-cost-sensitive-machine-learning-24b8760d35d9) will also be of help.

Thank you.

**Comment by Uthmanic** [comment]
Okay, thank you. I will look into it

**Pull request merged**
